# Generated by Django 3.2 on 2021-04-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rz', models.CharField(max_length=7)),
                ('znacka', models.CharField(max_length=100)),
                ('km', models.IntegerField()),
                ('tk', models.DateTimeField()),
            ],
        ),
    ]
