# Generated by Django 3.2 on 2021-04-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=25)),
                ('prijmeni', models.CharField(max_length=100)),
                ('ridicsky_prukaz', models.CharField(max_length=15)),
                ('datum_narozeni', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='auto',
            name='tk',
            field=models.DateField(),
        ),
    ]
