# Generated by Django 3.2 on 2021-04-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_auto_20210419_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vypujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vypujceni', models.DateTimeField()),
                ('vraceni', models.DateTimeField()),
                ('cena', models.IntegerField()),
            ],
        ),
    ]
